### PR TITLE
Some more skins for Female champs 

### PR DESCRIPTION
**Pull request by LiseThistle**
Skins for champs like: Briar, Seraphine, Akali, Tristana, Soraka, Ahri, Irelia, Caitlyn, Senna, and Lux. As well as additional skins for Nunu, Veigar, and Ezreal that I thought were missing from the folders.

### CODE REVIEW

**Comment by koobzaar** [comment]
Could you change the file extension to just .fantome and not .fantome.zip?

The files work normally (I've even tested a few). And I know that, according to the [definition of the .fantome file](https://github.com/LeagueToolkit/Fantome/wiki/Mod-File-Format), it is nothing more than a .zip file with a defined structure of folders and files inside, just renamed later from .zip to .fantome.

But the intention behind this is just to maintain the repository's file standard (they're all .fantome).

Don't worry about the “- Copy” in the file name. As for that, I use Powertoys and remove them.

Thank you!

**Comment by LiseThistle** [comment]
I can't change the names of the files without extracting them it seems. And once I extract them, the .zip part of the file is gone because it's no longer a compressed file. Even if I check the view file extension names, it won't let me change the file extensions at all for some reason T_T Sorry, I don't know whats wrong or what to do. I went in instead and just extracted a lot of the compressed files :/

**Comment by koobzaar** [comment]
It's normal to be prompted that changing the file extension will corrupt the file - but Windows is actually wrong. You don't need to extract them, just enable Show file extension and rename it.

But don't worry. I'll aprove your PR and do it by myself, then. Thank you for your contribution! 😊

**Comment by LiseThistle** [comment]
Okay then lol sorry i couldn't be of help in that regard! I have more files too for other champs that I got mostly from a discord server. I'll add them at a later time when i've rested, I have to see which champs are missing and which ones I have.

**Pull request merged**
