### PR TITLE
Added 2 New Arcane Skins

### PR DESCRIPTION
**Pull request by Emsumaa**
Arcane Brawler Vi
Arcane Survivor Jayce

### CODE REVIEW

**Comment by koobzaar** [comment]
But we already have those skins - T1, Coven, Frightnight, Cafe Cuties and PsyOps. What exactly changed?

Also your PR says "Added 2 new arcane skins" but I cannot see any new Arcane skins in the changed files.

**Comment by Emsumaa** [comment]
these are the new arcane season 2 skins, they came out today

**Comment by Emsumaa** [comment]
Wait I checked, and I have no idea why the arcane skins are not in there. I wanted to upload the other skins you currently see in there like a month ago but I didnt know how to. And today I tried it again and it seems that these skins are still in there... Idk sorry

**Comment by Emsumaa** [comment]
How tf do I delete my branch and make like a clean install?

**Comment by koobzaar** [comment]
Hello!

Git and GitHub can be a little frustrating sometimes.

It looks like the changes you made weren't uploaded because you likely forgot two important steps:
1. Create a commit to save your changes 
2. Push the commit to the remote repository you forked.

Let me break this down in simple terms:

A "commit" is like taking a snapshot of your project at a specific moment. Think of it as saving your work, but in a way that keeps track of all the changes you've made. When you make changes to your files, you need to:
- Stage your changes (tell git which files you want to save)
- Create a commit (take that snapshot with a description of what you changed)
- Push the commit to the remote repository (upload your changes to GitHub)

For people who aren't developers and find this technical process challenging, I recommend using GitHub Desktop. It makes version control much easier and more user-friendly. It provides a visual interface that simplifies the process of managing your code and tracking changes.

Regarding updating your repository, you can use the command `git pull`. This command brings the most recent changes from the main repository. However, since you have existing changes in your branch, you'll need to do a bit more:
- You might need to use `git rebase` to update your branch with the latest version
- Or you may want to discard your current local changes

If this sounds overwhelming, there are many beginner-friendly tutorials that can help you learn how to use GitHub Desktop and understand git in a simpler way.

**Pull request closed without merging**
